const games = [
    { teamAid: 0, teamA: "Alabama", teamBid:1, teamB: "TAMU-CC/SEMO" },
    { teamAid: 2, teamA: "Maryland", teamBid:3, teamB: "West Virginia" },
    { teamAid: 4, teamA: "San Diego", teamBid:5, teamB: "Charleston" },
    { teamAid: 6, teamA: "Virginia", teamBid:7, teamB: "Furman" },
    { teamAid: 8, teamA: "Creighton", teamBid:9, teamB: "NC State" },
    { teamAid: 10, teamA: "Baylor", teamBid:11, teamB: "UCSB" },
    { teamAid: 12, teamA: "Missouri", teamBid:13, teamB: "Utah St." },
    { teamAid: 14, teamA: "Arizona", teamBid:15, teamB: "Princeton" },
    { teamAid: 16, teamA: "Purdue", teamBid:17, teamB: "Texas Southern/FDU" },
    { teamAid: 18, teamA: "Memphis", teamBid:19, teamB: "Florida Atlantic" },
    { teamAid: 20, teamA: "Duke", teamBid:21, teamB: "Oral Roberts" },
    { teamAid: 22, teamA: "Tennessee", teamBid:23, teamB: "Louisiana" },
    { teamAid: 24, teamA: "Kentucky", teamBid:25, teamB: "Providence" },
    { teamAid: 26, teamA: "Kansas St.", teamBid:27,teamB: "Montana" },
    { teamAid: 28, teamA: "Michigan St.", teamBid:29,teamB: "USC" },
    { teamAid: 30, teamA: "Marguette", teamBid:31,teamB: "Vermont" },
    { teamAid: 32, teamA: "Houston", teamBid:33,teamB: "Northern Ky." },
    { teamAid: 34, teamA: "Iowa", teamBid:35,teamB: "Auburn" },
    { teamAid: 36, teamA: "Miami (FL)", teamBid:37,teamB: "Drake" },
    { teamAid: 38, teamA: "Indiana", teamBid:39,teamB: "Kent St." },
    { teamAid: 40, teamA: "Iowa St.", teamBid:41,teamB: "Mississipi St./Pitt" },
    { teamAid: 42, teamA: "Xavier", teamBid:43,teamB: "Kennesaw St." },
    { teamAid: 44, teamA: "Texas A&M", teamBid:45,teamB: "Penn St." },
    { teamAid: 46, teamA: "Texas", teamBid:47,teamB: "Colgate" },
    { teamAid: 48, teamA: "Kansas", teamBid:49,teamB: "Howard" },
    { teamAid: 50, teamA: "Arkansas", teamBid:51,teamB: "Illinois" },
    { teamAid: 52, teamA: "Saint Mary's", teamBid:53,teamB: "VCU" },
    { teamAid: 54, teamA: "UConn", teamBid:55,teamB: "Iona" },
    { teamAid: 56, teamA: "TCU", teamBid:57,teamB: "Arizona St./Nevada" },
    { teamAid: 58, teamA: "Gonzaga", teamBid:59,teamB: "Grand Canyon" },
    { teamAid: 60, teamA: "Northwestern", teamBid:61,teamB: "Boise St." },
    { teamAid: 62, teamA: "UCLA", teamBid:63,teamB: "UNC Asheville" }
]
export default games;