const games = [
    { id: 1, teamA: "Team A", teamB: "Team B" },
    { id: 2, teamA: "Team A", teamB: "Team B" },
    { id: 3, teamA: "Team A", teamB: "Team B" },
    { id: 4, teamA: "Team A", teamB: "Team B" },
    { id: 5, teamA: "Team A", teamB: "Team B" },
    { id: 6, teamA: "Team A", teamB: "Team B" },
    { id: 7, teamA: "Team A", teamB: "Team B" },
    { id: 8, teamA: "Team A", teamB: "Team B" },
    { id: 9, teamA: "Team A", teamB: "Team B" },
    { id: 10, teamA: "Team A", teamB: "Team B" },
    { id: 11, teamA: "Team A", teamB: "Team B" },
    { id: 12, teamA: "Team A", teamB: "Team B" },
    { id: 13, teamA: "Team A", teamB: "Team B" },
    { id: 14, teamA: "Team A", teamB: "Team B" },
    { id: 15, teamA: "Team A", teamB: "Team B" },
    { id: 16, teamA: "Team A", teamB: "Team B" },
    { id: 17, teamA: "Team A", teamB: "Team B" },
    { id: 18, teamA: "Team A", teamB: "Team B" },
    { id: 19, teamA: "Team A", teamB: "Team B" },
    { id: 20, teamA: "Team A", teamB: "Team B" },
    { id: 21, teamA: "Team A", teamB: "Team B" },
    { id: 22, teamA: "Team A", teamB: "Team B" },
    { id: 23, teamA: "Team A", teamB: "Team B" },
    { id: 24, teamA: "Team A", teamB: "Team B" },
    { id: 25, teamA: "Team A", teamB: "Team B" },
    { id: 26, teamA: "Team A", teamB: "Team B" },
    { id: 27, teamA: "Team A", teamB: "Team B" },
    { id: 28, teamA: "Team A", teamB: "Team B" },
    { id: 29, teamA: "Team A", teamB: "Team B" },
    { id: 30, teamA: "Team A", teamB: "Team B" },
    { id: 31, teamA: "Team A", teamB: "Team B" },
    { id: 32, teamA: "Team A", teamB: "Team B" }  
]  
export default games;